# Generated by Django 3.0.3 on 2023-11-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0002_auto_20231123_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='access',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
